class LocalizationService:
    """خدمة إدارة النصوص ودعم متعدد اللغات"""

    _translations = {
        "ar": {
            "title": "صانع رموز QR المتقدم",
            "select_type": "اختر نوع المحتوى:",
            "types": ["نص فقط", "معلومات شخصية / بطاقة أعمال", "رابط موقع (URL)", "رابط صورة", "رابط فيديو"],
            "enter_data": "أدخل البيانات أو الرابط:",
            "btn_generate": "إنشاء رمز QR",
            "qr_placeholder": "سيظهر الرمز هنا",
            "btn_save": "حفظ كصورة PNG",
            "btn_print": "طباعة الرمز",
            "lang_btn": "اللغات / Languages",
            "err_title": "تنبيه",
            "err_msg": "يرجى إدخال نص أو رابط أولاً!",
            "success_title": "نجاح",
            "success_msg": "تم حفظ صورة PNG بنجاح!",
            "save_dialog_title": "حفظ رمز QR",
            "qr_customs": "تخصيص الرمز",
            "fill_color": "لون الرمز:",
            "back_color": "لون الخلفية:",
        },
        "en": {
            "title": "Advanced QR Code Generator",
            "select_type": "Select Content Type:",
            "types": ["Plain Text", "Personal Info / Digital Card", "Website (URL)", "Image Link", "Video Link"],
            "enter_data": "Enter Data or Link:",
            "btn_generate": "Generate QR Code",
            "qr_placeholder": "QR Code will appear here",
            "btn_save": "Save as PNG",
            "btn_print": "Print QR Code",
            "lang_btn": "Languages",
            "err_title": "Warning",
            "err_msg": "Please enter text or link first!",
            "success_title": "Success",
            "success_msg": "PNG image saved successfully!",
            "save_dialog_title": "Save QR Code",
            "qr_customs": "QR Customization",
            "fill_color": "QR Color:",
            "back_color": "Background:",
        },
        "zh": {
            "title": "高级二维码生成器",
            "select_type": "选择内容类型：",
            "types": ["纯文本", "个人信息 / 数字名片", "网站链接", "图片链接", "视频链接"],
            "enter_data": "输入数据或链接：",
            "btn_generate": "生成二维码",
            "qr_placeholder": "二维码将显示在这里",
            "btn_save": "保存为 PNG",
            "btn_print": "打印二维码",
            "lang_btn": "语言 (Languages)",
            "err_title": "警告",
            "err_msg": "请先输入文本或链接！",
            "success_title": "成功",
            "success_msg": "PNG 图片保存成功！",
            "save_dialog_title": "保存二维码",
            "qr_customs": "自定义二维码",
            "fill_color": "二维码颜色：",
            "back_color": "背景颜色：",
        },
        "fr": {
            "title": "Générateur de QR Code Avancé",
            "select_type": "Sélectionnez le type :",
            "types": ["Texte Brut", "Info Personnelle / Carte Numérique", "Lien Web", "Lien Image", "Lien Vidéo"],
            "enter_data": "Entrez les données :",
            "btn_generate": "Générer le QR Code",
            "qr_placeholder": "Le QR Code apparaîtra ici",
            "btn_save": "Enregistrer en PNG",
            "btn_print": "Imprimer le QR Code",
            "lang_btn": "Langues",
            "err_title": "Avertissement",
            "err_msg": "Veuillez d'abord saisir du texte ou un lien !",
            "success_title": "Succès",
            "success_msg": "Image PNG enregistrée avec succès !",
            "save_dialog_title": "Enregistrer le QR Code",
            "qr_customs": "Personnalisation",
            "fill_color": "Couleur QR :",
            "back_color": "Couleur Fond :",
        },
        "ru": {
            "title": "Продвинутый генератор QR-кодов",
            "select_type": "Выберите тип контента:",
            "types": ["Обычный текст", "Личная инфо / Визитка", "Ссылка на сайт", "Ссылка на фото", "Ссылка на видео"],
            "enter_data": "Введите данные или ссылку:",
            "btn_generate": "Создать QR-код",
            "qr_placeholder": "QR-код появится здесь",
            "btn_save": "Сохранить как PNG",
            "btn_print": "Печать QR-кода",
            "lang_btn": "Языки",
            "err_title": "Предупреждение",
            "err_msg": "Пожалуйста, сначала введите текст или ссылку!",
            "success_title": "Успех",
            "success_msg": "Изображение PNG успешно сохранено!",
            "save_dialog_title": "Сохранить QR-код",
            "qr_customs": "Настройка QR-кода",
            "fill_color": "Цвет QR:",
            "back_color": "Цвет фона:",
        },
        "hi": {
            "title": "उन्नत क्यूआर कोड जनरेटर",
            "select_type": "सामग्री का प्रकार चुनें:",
            "types": ["साधारण पाठ", "व्यक्तिगत जानकारी / डिजिटल कार्ड", "वेबसाइट लिंक", "इमेज लिंक", "वीडियो लिंक"],
            "enter_data": "डेटा या लिंक दर्ज करें:",
            "btn_generate": "क्यूआर कोड बनाएं",
            "qr_placeholder": "क्यूआर कोड यहां दिखाई देगा",
            "btn_save": "PNG के रूप में सहेजें",
            "btn_print": "क्यूआर कोड प्रिंट करें",
            "lang_btn": "भाषाएं",
            "err_title": "चेतावनी",
            "err_msg": "कृपया पहले टेक्स्ट या लिंक दर्ज करें!",
            "success_title": "सफलता",
            "success_msg": "PNG छवि सफलतापूर्वक सहेजी गई!",
            "save_dialog_title": "क्यूआर कोड सहेजें",
            "qr_customs": "क्यूआर अनुकूलन",
            "fill_color": "क्यूआर रंग:",
            "back_color": "पृष्ठभूमि रंग:",
        }
    }

    def __init__(self, default_lang: str = "ar"):
        self.current_lang = default_lang

    def set_language(self, lang_code: str) -> str:
        if lang_code in self._translations:
            self.current_lang = lang_code
        return self.current_lang

    def get_text(self, key: str):
        return self._translations.get(self.current_lang, {}).get(key, key)